#!/bin/bash

PROJECT=''

if [ $(git rev-parse --is-bare-repository) = true ]
then
    PROJECT=$(basename "$PWD")
else
    echo "Not running inside a bare repository; skipping..."
    exit
fi

while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        pip install --user git+ssh://git@github.com/earaujoassis/deployment
        ploy receive $PROJECT $oldrev $newrev
    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
