#!/bin/bash

set -e

PROJECT=''

if [ $(git rev-parse --is-bare-repository) = true ]
then
    PROJECT=$(basename "$PWD")
else
    echo "Not running inside a bare repository; skipping..."
    exit
fi

while read oldrev newrev ref
do
    if [[ $ref =~ .*/master$ ]];
    then
        pip install --user https://github.com/earaujoassis/deployment/archive/0.1.7.zip
        export PATH=$(python2 -m site --user-base)/bin:$PATH
        ploy receive $PROJECT $oldrev $newrev
    else
        echo "Ref $ref successfully received. Doing nothing: only the master branch may be deployed on this server."
    fi
done
